spring:
  application:
    name: hrms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root

server:
  port: 9999

mybatis:
  mapper-locations: classpath:/mapper/*.xml
