spring:
  application:
    name: hrms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root

  resources:
    static-locations: classpath:/templates/,classpath:/static/
#  main:
#    allow-bean-definition-overriding: true

server:
  port: 9999

mybatis:
  mapper-locations: classpath:/mapper/*.xml

sumaojin:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
